import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google"; //구글폰트 추가
//전역 css
import "@/styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";

const roboto = Roboto({ subsets: ["latin"],weight:["400","500","700"]})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <SideNavigation/> 
        {children}
      </body>
    </html>
  );
}
